#!/bin/bash

CORES=`cat /proc/cpuinfo | grep processor | wc -l`

apt-get install libblkid-dev liblzo2-dev asciidoc

cd /usr/src
git clone git://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git
cd btrfs-progs
make 
make install

