#!/bin/bash

CORES=`cat /proc/cpuinfo | grep processor | wc -l`

apt-get install libblkid-dev liblzo2-dev asciidoc e2fslibs-dev pkg-config libacl1-dev

cd /usr/src

git clone git://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git

cd btrfs-progs

./autogen.sh
./configure --prefix=/usr
make -j${CORES}
make install


