#!/bin/bash

CORES=`cat /proc/cpuinfo | grep processor | wc -l`

cd /usr/src
git clone https://github.com/zfsonlinux/spl.git
cd spl
./autogen.sh
./configure
#make 
make -j${CORES} deb
#make -j${CORES} deb-utils deb-kmod
dpkg -i *.deb
