#!/bin/bash

CORES=`cat /proc/cpuinfo | grep processor | wc -l`


cd /usr/src
git clone https://github.com/zfsonlinux/zfs.git
cd zfs
./autogen.sh
./configure --with-spl=/usr/src/spl --with-spl-obj=/usr/src/spl-0.6.3/3.18.3
make -j${CORES} deb-utils deb-kmod
